spring:
  cloud:
    gateway:
      routes:
       - id: baidu_rouce
         uri: https://www.baidu.com
         predicates:
         - Query=url,baidu
       - id: qq_rouce
         uri: https://www.qq.com
         predicates:
         - Query=url,qq